from __future__ import annotations

from enum import StrEnum


class ProductionRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    PARTIAL_FAILED = "PARTIAL_FAILED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ProductionStageStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AgentTaskStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ProductionStageType(StrEnum):
    BOOK_PLANNING = "BOOK_PLANNING"

    CHAPTER_PLANNING = "CHAPTER_PLANNING"
    CHAPTER_RESEARCH = "CHAPTER_RESEARCH"
    CHAPTER_WRITING = "CHAPTER_WRITING"
    CHAPTER_REVIEW = "CHAPTER_REVIEW"
    CHAPTER_EDITING = "CHAPTER_EDITING"
    CHAPTER_REVISION = "CHAPTER_REVISION"
    CHAPTER_READER_TEST = "CHAPTER_READER_TEST"
    CHAPTER_FINALIZATION = "CHAPTER_FINALIZATION"

    BOOK_REVIEW = "BOOK_REVIEW"
    BOOK_FINALIZATION = "BOOK_FINALIZATION"
    EXPORT = "EXPORT"


class AgentRole(StrEnum):
    PLANNER = "PLANNER"
    RESEARCHER = "RESEARCHER"
    WRITER = "WRITER"

    FACT_REVIEWER = "FACT_REVIEWER"
    STRUCTURE_REVIEWER = "STRUCTURE_REVIEWER"
    STYLE_REVIEWER = "STYLE_REVIEWER"

    REVIEW_AGGREGATOR = "REVIEW_AGGREGATOR"
    EDITOR = "EDITOR"
    REVISER = "REVISER"
    READER = "READER"

    VISUAL_PLANNER = "VISUAL_PLANNER"
    DIAGRAM_AGENT = "DIAGRAM_AGENT"
    QA_AGENT = "QA_AGENT"


class ProductionArtifactType(StrEnum):
    BOOK_PLAN = "BOOK_PLAN"
    CHAPTER_PLAN = "CHAPTER_PLAN"
    EVIDENCE_PACK = "EVIDENCE_PACK"
    RESEARCH_REPORT = "RESEARCH_REPORT"

    CHAPTER_DRAFT = "CHAPTER_DRAFT"

    FACT_REVIEW_REPORT = "FACT_REVIEW_REPORT"
    STRUCTURE_REVIEW_REPORT = "STRUCTURE_REVIEW_REPORT"
    STYLE_REVIEW_REPORT = "STYLE_REVIEW_REPORT"
    AGGREGATED_REVIEW_REPORT = "AGGREGATED_REVIEW_REPORT"

    EDITORIAL_DECISION = "EDITORIAL_DECISION"
    REVISED_CHAPTER = "REVISED_CHAPTER"
    READER_REPORT = "READER_REPORT"

    VISUAL_PLAN = "VISUAL_PLAN"
    DIAGRAM = "DIAGRAM"

    QA_REPORT = "QA_REPORT"
    FINAL_CHAPTER = "FINAL_CHAPTER"
    FINAL_BOOK = "FINAL_BOOK"
    EXPORT_FILE = "EXPORT_FILE"


class PublishingEventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    RUN_STARTED = "RUN_STARTED"
    RUN_PAUSED = "RUN_PAUSED"
    RUN_RESUMED = "RUN_RESUMED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_CANCELLED = "RUN_CANCELLED"

    STAGE_CREATED = "STAGE_CREATED"
    STAGE_STARTED = "STAGE_STARTED"
    STAGE_COMPLETED = "STAGE_COMPLETED"
    STAGE_FAILED = "STAGE_FAILED"
    STAGE_SKIPPED = "STAGE_SKIPPED"

    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRIED = "TASK_RETRIED"

    ARTIFACT_CREATED = "ARTIFACT_CREATED"

    REVIEW_ISSUE_CREATED = "REVIEW_ISSUE_CREATED"
    DECISION_REQUIRED = "DECISION_REQUIRED"
    DECISION_RESOLVED = "DECISION_RESOLVED"

    AGENT_MESSAGE_CREATED = "AGENT_MESSAGE_CREATED"
